const FETCH_REGISTRATIONS = "FETCH_REGISTRATIONS";
const FETCH_REGISTRATIONS_SUCEESS = "FETCH_REGISTRATIONS_SUCEESS";
const REGIST_CONTEST = "REGIST_CONTEST";
const LOADING = "LOADING";

export default {
  FETCH_REGISTRATIONS,
  FETCH_REGISTRATIONS_SUCEESS,
  REGIST_CONTEST,
  LOADING,
};
