const FETCH_PROBLEMS = "FETCH_PROBLEMS";
const FETCH_PROBLEMS_SUCEESS = "FETCH_PROBLEMS_SUCEESS";
const LOADING = "LOADING";

export default {
  FETCH_PROBLEMS,
  FETCH_PROBLEMS_SUCEESS,
  LOADING,
};
