const FETCH_SUBMISSIONS = "FETCH_SUBMISSIONS";
const FETCH_SUBMISSIONS_SUCEESS = "FETCH_SUBMISSIONS_SUCEESS";
const LOADING = "LOADING";

export default {
  FETCH_SUBMISSIONS,
  FETCH_SUBMISSIONS_SUCEESS,
  LOADING,
};
