const FETCH_SUBMISSIONS = "FETCH_SUBMISSIONS";
const FETCH_SUBMISSIONS_SUCEESS = "FETCH_SUBMISSIONS_SUCEESS";
const LOADING = "LOADING";
const CHANGE_SUBMISSIONS_PAGE = "CHANGE_SUBMISSIONS_PAGE";

export default {
  FETCH_SUBMISSIONS,
  FETCH_SUBMISSIONS_SUCEESS,
  LOADING,
  CHANGE_SUBMISSIONS_PAGE,
};
