const FETCH_CONTESTS = "FETCH_CONTESTS";
const FETCH_CONTESTS_SUCEESS = "FETCH_CONTESTS_SUCEESS";
const LOADING = "LOADING";

export default {
  FETCH_CONTESTS,
  FETCH_CONTESTS_SUCEESS,
  LOADING,
};
