const FETCH_CONTESTS = "FETCH_CONTESTS";
const FETCH_CONTESTS_SUCEESS = "FETCH_CONTESTS_SUCEESS";
const FETCH_CONTEST_SUCCESS = "FETCH_CONTEST_SUCCESS";
const FETCH_FAILED = "FETCH_FAILED";
const LOADING = "LOADING";

export default {
  FETCH_CONTESTS,
  FETCH_CONTESTS_SUCEESS,
  FETCH_CONTEST_SUCCESS,
  FETCH_FAILED,
  LOADING,
};
