const FETCH_RANKINGS = "FETCH_RANKINGS";
const FETCH_RANKINGS_SUCEESS = "FETCH_RANKINGS_SUCEESS";
const LOADING = "LOADING";

export default {
  FETCH_RANKINGS,
  FETCH_RANKINGS_SUCEESS,
  LOADING,
};
