const FETCH_RANKINGS = "FETCH_RANKINGS";
const FETCH_RANKINGS_SUCEESS = "FETCH_RANKINGS_SUCEESS";
const LOADING = "LOADING";
const CHANGE_PAGE = "CHANGE_PAGE";

export default {
  FETCH_RANKINGS,
  FETCH_RANKINGS_SUCEESS,
  LOADING,
  CHANGE_PAGE,
};
