const FETCH_RANKINGS = "FETCH_RANKINGS";
const FETCH_RANKINGS_SUCEESS = "FETCH_RANKINGS_SUCEESS";
const LOADING = "LOADING";
const CHANGE_RANKING_PAGE = "CHANGE_RANKING_PAGE";

export default {
  FETCH_RANKINGS,
  FETCH_RANKINGS_SUCEESS,
  LOADING,
  CHANGE_RANKING_PAGE,
};
