const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
const FETCH_NOTIFICATIONS_SUCEESS = "FETCH_NOTIFICATIONS_SUCEESS";
const LOADING = "LOADING";

export default {
  FETCH_NOTIFICATIONS,
  FETCH_NOTIFICATIONS_SUCEESS,
  LOADING,
};
